Added core components
Vimian/smart-door-lock pull request #1
Opened 2024-03-26 00:55 UTC by Vimian

2024-03-28 06:53 UTC, SSpedsbjerg requested changes

2024-03-28 06:53 UTC, SSpedsbjerg commented on src/main/main.c
> +        if (isAlarm || (!isAlarm && alarm_state == 0)) {
Du vil aldrig komme ind i hvor isAlarm er sand og !isAlarm er sand
simplificere det til (isAlarm || alarm_state == 0)

2024-03-28 06:53 UTC, SSpedsbjerg commented on src/main/main.c
> +void funlocking() {
hvad er meningen med 'f'?

2024-03-28 06:53 UTC, SSpedsbjerg commented on src/main/main.c
> +void falarm() {
samme her med 'f'

2024-03-28 06:53 UTC, SSpedsbjerg commented on src/main/main.c
> +void TaskBlink (void *pvParameters) {
pvParameters? hvad er grunden til denne reference?

2024-03-28 06:53 UTC, SSpedsbjerg commented on src/main/main.c
> +void ListenToButtons (void *pvParameters) {
void reference uden nogen specifik grund

2024-03-28 06:53 UTC, SSpedsbjerg commented on src/main/main.c
Ikke for at være den gut, men hvordan du skifter mellem pascal, camel og snakecase er frustrende
Jeg vil sige at vi bare bør gå udelukkende snakecase for det er hvad man gør i C/C++

2024-03-28 06:57 UTC, SSpedsbjerg commented on src/main/main.c
> +void TaskBlink (void *pvParameters) {
nvm er nok noget som esp-32 har påkrævet

2024-03-29 14:29 UTC, vimian commented on src/main/main.c
> +        if (isAlarm || (!isAlarm && alarm_state == 0)) {
Fair, good catch

2024-03-29 14:31 UTC, vimian commented on src/main/main.c
> +void funlocking() {
unlocking er både en channel og en action, så satte f foran fordi man kan ikke have en variable og function med samme navn.

2024-03-29 14:42 UTC, vimian commented on src/main/main.c
Tænkte C ville være samme som JAVA, så gik med

pascal til function som ikke er action function
camel til variable og action function
snakecase er kun ting som er fra libaries

Har ændret alt til snakecase nu.

2024-03-29 14:43 UTC, Vimian commented on src/main/main.c
> +void funlocking() {
Har ændret dem til

func_unlocking og func_alarm.

2024-03-29 14:54 UTC, GachiRoss approved these changes, later dismissed
SeemsGood

2024-03-29 14:56 UTC, GachiRoss approved these changes

2024-03-31 08:21 UTC, SSpedsbjerg approved these changes

2024-03-31 09:14 UTC, merged