Implemented BLE for IPhone and android can use bluetooth
Vimian/smart-door-lock pull request #10
Opened 2024-05-05 16:41 UTC by GachiRoss

replacing bluetooth classic with BLE

2024-05-05 17:04 UTC, SSpedsbjerg requested changes

2024-05-05 17:04 UTC, SSpedsbjerg commented on src/main/main.c
> +    } while (0);
what is the reason for running a while loop only once?

2024-05-05 17:04 UTC, SSpedsbjerg commented on src/main/main.c
> +            if (adv_config_done == 0){
geussing this refence a enum, could that be clear so it is readable, cause I don't know what 0 means

2024-05-05 17:04 UTC, SSpedsbjerg commented on src/main/main.c
> +static void gatts_event_handler(esp_gatts_cb_event_t event, esp_gatt_if_t gatts_if, esp_ble_gatts_cb_param_t *param)
Reason for this method?

2024-05-05 17:04 UTC, SSpedsbjerg commented on src/main/main.c
> +#define ADV_CONFIG_FLAG             (1 << 0)
What is the reason for making bit-shifts here?

2024-05-05 17:04 UTC, SSpedsbjerg commented on src/main/main.c
> +#define SCAN_RSP_CONFIG_FLAG        (1 << 1)
bit-shift

2024-05-05 17:04 UTC, SSpedsbjerg commented on src/main/main.c
> +    0xfb, 0x34, 0x9b, 0x5f, 0x80, 0x00, 0x00, 0x80, 0x00, 0x10, 0x00, 0x00, 0xFF, 0x00, 0x00, 0x00,
pre-declared ID? these values seem random

2024-05-27 20:35 UTC, Vimian approved these changes

2024-05-27 20:50 UTC, merged