Feature 2fac pairing
Vimian/smart-door-lock pull request #9
Opened 2024-05-05 13:30 UTC by SSpedsbjerg

2024-05-06 08:33 UTC, vimian commented on src/main/main.c
> +    if (gpio_get_level(PIN_AUTH) == 0) { //pressed
Should be moved together with the other buttons in listen_to_buttons()

2024-05-06 09:15 UTC, Vimian commented on src/main/main.c
> +    } else if (unlock_timer < 10 && !is_opened && is_authenticated()) {
move this to bt connection

if (is_locked && !unlocking && !manual_lock && is_authenticated()) {
                unlocking = true;
                unlock_timer = 0;

2024-05-12 12:40 UTC, Vimian approved these changes

2024-05-12 13:19 UTC, GachiRoss requested changes
reason for adding lines ?

2024-05-12 13:19 UTC, GachiRoss commented on src/main/main.c
> +
unecesary lines

2024-05-12 13:21 UTC, Vimian commented on src/main/main.c
> +
It is okay

2024-05-12 13:22 UTC, GachiRoss approved these changes

2024-05-12 13:23 UTC, merged